### ISSUE TITLE
Not sure where to edit - error Chap 4 solution

### ISSUE THREAD

**Issue by dvanic** [geocompr/geocompkg#1]
Hi! Not sure where to put the pull request for the [solutions.html](https://geocompr.github.io/geocompkg/articles/solutions04.html)

Code as in solutions:

    canterbury = nz %>% filter(Name == "Canterbury Region")
    canterbury_height = nz_height[canterbury, ]
    nrow(canterbury_height) # answer: 61

Problem:

     Canterbury Region" %in% nz$Name
     [1] FALSE
     "Canterbury" %in% nz$Name
     [1] TRUE

Suggested solution:

    canterbury = nz %>% filter(Name == "Canterbury")
    canterbury_height = nz_height[canterbury, ]
    nrow(canterbury_height) # answer: 70

**Comment by Robinlovelace** [comment]
Well spotted. I can reproduce the issue, as shown in the following reprex:

``` r
library(spData)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
canterbury = nz %>% filter(Name == "Canterbury Region")
canterbury_height = nz_height[canterbury, ]
nrow(canterbury_height) # answer: 61
#> [1] 0
"Canterbury Region" %in% nz$Name
#> [1] FALSE
"Canterbury" %in% nz$Name
#> [1] TRUE
canterbury = nz %>% filter(Name == "Canterbury")
canterbury_height = nz_height[canterbury, ]
nrow(canterbury_height) # answer: 70
#> [1] 70
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

You can edit the solutions to c4 here: https://github.com/geocompr/geocompkg/blob/master/vignettes/solutions04.Rmd (note: this is linked-to in the Source: `vignettes/solutions04.Rmd` bit at the top of the [page](https://geocompr.github.io/geocompkg/articles/solutions04.html) mention.

A PR implementing the fix you recommend would be most appreciated. Many thanks!

**Comment by Robinlovelace** [comment]
Just realised, this was fixed by @Nowosad ages ago in this commit (many thanks!): https://github.com/geocompr/geocompkg/commit/037127e94543b5e7afcb3cfacf62abe2721fb75f#diff-431f2cd93e3388ad1c21e938b4d4c688

@dvanic if you find any other issues please feel free to open another issue.
