### ISSUE TITLE
Build fails on Travis

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/geocompkg#10]
Any ideas @Nowosad ?

https://travis-ci.org/github/geocompr/geocompkg/builds/667385258#L9906

**Comment by Nowosad** [comment]
I think this is an issue with the recent version of **pkgdown** - see https://github.com/r-lib/pkgdown/issues/1274 and https://github.com/r-lib/pkgdown/issues/1275. I would suggest to wait for the new version of **pkgdown** on CRAN.

**Comment by Nowosad** [comment]
Travis is not here anymore - I moved the repo to gh actions.

**Comment by Robinlovelace** [comment]
:tada: :champagne:
