### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompkg#22]
@Robinlovelace do you have any idea what is wrong here? - https://github.com/geocompr/geocompkg/actions/runs/237323887

**Comment by Robinlovelace** [comment]
Not sure, maybe a temporary issue associated with GH access tokens? The jobs should be re-running now.

**Comment by Robinlovelace** [comment]
That didn't fix it... 

https://github.com/geocompr/geocompkg/runs/1116126708#step:9:15

**Comment by Robinlovelace** [comment]
To avoid running us-map.Rmd:

![image](https://user-images.githubusercontent.com/1825120/93193995-78ce2e80-f73f-11ea-805d-d59f8d9773c3.png)

**Comment by Robinlovelace** [comment]
Good news @Nowosad, recent changes have meant the site builds in ~10 minutes, down from 1 hr :tada:
