### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/geocompkg#28]
Heads-up @Nowosad, just noticed this is failing on the universe builds: https://github.com/r-universe/geocompr/runs/3383708750?check_suite_focus=true and maybe on actions too...

**Comment by Nowosad** [comment]
Fixed - https://github.com/geocompr/geocompkg/actions.

**Comment by Robinlovelace** [comment]
Aha, well diagnosed and good fix https://github.com/geocompr/geocompkg/commit/2b0c54df810b36271060d510608277a93e9dab66
