### ISSUE TITLE
Use of the tidyverse package in the DESCRIPTION

### ISSUE THREAD

**Issue by Nowosad** [geocompr/geocompkg#5]
@Robinlovelace @jannes-m would it be possible to replace the tidyverse package in the DESCRIPTION (https://github.com/geocompr/geocompkg/blob/d4af9b8c3dca6bf4f9e28083f1d71646f0cf9d9c/DESCRIPTION#L54) with a set of packages that we actually use? What do you thing?

**Comment by Robinlovelace** [comment]
I think that is a good plan. To my knowledge it's only `purrr` and `dplyr` that we use. Possibly `readr` also. :+1: from me!

**Comment by Nowosad** [comment]
Ok, let's see what is going to happen;) https://github.com/geocompr/geocompkg/commit/b0f692e6c3037eabfc2f1c4da51b4e8faa8df172

**Comment by Nowosad** [comment]
It seems to work well. (But please recheck the book @Robinlovelace )

**Comment by Robinlovelace** [comment]
Great work and good practice. Thank you Jakub.
