### ISSUE TITLE
Build is crashing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/geocompkg#7]
See here: https://travis-ci.org/geocompr/geocompkg/jobs/559948483#L9220

```
 SUMMARY: processing the following files failed:
  ‘cast.Rmd’ ‘solutions13.Rmd’
```

Any ideas @Nowosad ?

**Comment by Nowosad** [comment]
Should be fine now.

**Comment by Nowosad** [comment]
@Nowosad this is only a work-around. I think the issue is deeper here - I am getting closer to the source of the problem every second;)

**Comment by Nowosad** [comment]
https://github.com/rspatial/raster/issues/62

**Comment by Nowosad** [comment]
https://travis-ci.org/geocompr/geocompkg/builds
