### ISSUE TITLE
data from zensus in ch13 no longer accessible

### ISSUE THREAD

**Issue by steelexu** [geocompr/geocompkg#9]
https://www.zensus2011.de don't provide data for Geomarketing chapter

Thanks for reading your book.

**Comment by jannes-m** [comment]
Can you please be a bit more specific, I am not sure what you are referring to. I just ran the code  found in ch13 which downloads the census data:

```r
download.file("https://tinyurl.com/ybtpkwxz", 
              destfile = "census.zip", mode = "wb")
unzip("census.zip") # unzip the files
census_de = readr::read_csv2(list.files(pattern = "Gitter.csv"))
``` 
And it worked perfectly fine.

**Comment by Robinlovelace** [comment]
Confirmed, I can reproduce that, thanks @jannes-m. Does that resolve the issue for you @steelexu ?

**Comment by fireflygreen** [comment]
works now
Thanks!

**Comment by Robinlovelace** [comment]
Heads-up @jannes-m I think @steelexu was right. The data is still there but the units have changed:

![image](https://user-images.githubusercontent.com/1825120/76947904-33e74d80-68fe-11ea-9894-02e03fd0d533.png)

**Comment by Robinlovelace** [comment]
That seems the same as:

![image](https://user-images.githubusercontent.com/1825120/76947947-46fa1d80-68fe-11ea-8c4e-19f6411abc85.png)
